/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module "vue" {
  export interface GlobalComponents {
    HelloWorld: typeof import("./src/components/HelloWorld.vue")["default"];
    RouterLink: typeof import("vue-router")["RouterLink"];
    RouterView: typeof import("vue-router")["RouterView"];
    VarAppBar: typeof import("@varlet/ui")["_AppBarComponent"];
    VarAppBarx: typeof import("@varlet/ui")["_AppBarxComponent"];
    VarButton: typeof import("@varlet/ui")["_ButtonComponent"];
    VarForm: typeof import("@varlet/ui")["_FormComponent"];
    VarInput: typeof import("@varlet/ui")["_InputComponent"];
    VarSpace: typeof import("@varlet/ui")["_SpaceComponent"];
  }
}
